### ISSUE TITLE
Can't perform multiple page turns in a row

### ISSUE THREAD

**Issue by vonbathory** [swisspol/ComicFlow#83] opened 2015-03-29 15:37 UTC
It seems like you have a timer or something so you don't register page turn gestures for so many seconds or something.  This has been happening for a while now, I only just now decided to report it.  I don't recall this always being the case, so I don't know if it came about in the last 1 or 2 version updates or what.

Essentially if I swipe left from the right edge, it turns the page.  If I immediately swipe again, nothing happens.  I have to wait about 3 seconds to turn again.  Sometimes I want to 'flip back' a couple pages to see if I missed something important.  I realize I can use the little bar at the bottom to maneuver multiple pages, but then I have to tap once to bring it up, then get my big finger on the little dot then slowly track my giant finger, it's just not the way I like to do it.  (Which can be tough luck for me, that's a viable response.)

Anyway, I hope you take this concern under consideration.

Thanks!

**Comment by guesxy** [comment] 2015-03-29 15:55
Same thing for me, I think this is related to the other open bug (which I dont think was released as part of a newer version?) about the full cbr being rescanned... Definitely wasn't the case before!

**Comment by swisspol** [comment] 2015-03-29 17:09
This behavior has existed since ComicFlow 1.0 and has nothing to do with a timer or anything like that.

Loading comic pages can take time and depending on the underlying image size and performance of the iPad up to several seconds. There's no way around this. To ensure a smooth reading experience, ComicFlow always preloads the next page in the background while the user is reading the current page, so swiping to it is almost all the time instantaneous. When the next page is shown on screen, if you happen to want to swipe *immediately*, the app has to block until that next-next-page is ready.

@guesxy the bug you are referring to is #43 which is not something that can be easily fixed on the ComicFlow side. It's just "degenerated" CBR files.

**Closed by swisspol** 2015-03-29 17:09 UTC
Labels: question

**Comment by vonbathory** [comment] 2015-03-29 18:35
Thanks for the response. 
Not being familiar with the amount of memory being used, how excessive would it be to load up the entire comic into memory in the background?  Then clear out that memory when the user goes back to the library or when the app goes inactive?   Just tossing out ideas without really knowing the repercussions of said ideas.

**Comment by swisspol** [comment] 2015-03-29 18:41
Images inside comics are typically compressed (JPEG almost all the time) so a page scanned at 3 MP might take 150 KB on disk, but 3 * 1000 * 1000 * 4 bytes / pixel = 12 MB in memory once uncompressed and ready to display. So no it wont fit.

The swiping can be made more responsive by doing more fancy pre-loading but only up to a certain point as you're obviously still bound by CPU & I/O performance, and it would be a lot of work but no real benefit. The proof being that it took 4 years for someone to finally "complain" about this loading "delay" :) In practice, users don't hit this problem as they spend more than a few seconds on each page and don't attempt to scan the comic pages 1 by 1.

**Comment by guesxy** [comment] 2015-03-29 19:15
Regrading the "4 years no one complained", the unresponsiveness issue wasn't there before some 6 months ago. Any comics i was flicking through up were changing pages immediately. Now 95% of them dont. You might be right that its just the limitation of the CPU... If there is enough text on the page its not a big issue, but for action packed scenes it can get a bit annoying :D

**Comment by swisspol** [comment] 2015-03-29 19:23
You're just reading different comics with pages that take longer to preload (larger images, PDF instead of CBR, etc...).

ComicFlow last update was from October 2014 and its display code hasn't even been touched in the past 12 months and most likely past 2-3 years.

**Comment by guesxy** [comment] 2015-03-29 19:27
You most likely are right, I am just waiting for a chance when I get one that flicks ok, and then compare the difference to those that don't, as otherwise I think it's a great comic book viewer :)

**Comment by swisspol** [comment] 2015-03-29 19:40
Thanks!

Note that if you're swapping through pages at a speed of 10 pages per second and it takes 1 second to render a page, it's *physically impossible* to make it work short of 1) not rendering the pages at all or 2) preprocessing comics when adding them to the library to create fast-loading thumbnails for each page. IMO these 2 options are actually worse than the current limitation for a variety of reasons.

**Comment by vonbathory** [comment] 2015-03-29 21:44
guesxy, which iPad are you using out of curiosity?  Like you said, I don't recall this 'limitation' before. So part of me wonders if it's related to going to iOS 8, something about the new OS maybe?  I'm on a 3rd gen iPad.  Comic Zeal page turning is pretty fast, as is Chunky (although I'm not fond of how it loads pages).  Fear not, I'm still with ComicFlow because I still like it better than other readers I've tried.
Swisspol, I'm not looking at whipping through that many pages.  What I'm doing is a roughly a 1 second swipe (1 second between touching the iPad before I touch again to swipe again).  When I touchdown again and swipe again, it's not like it's slow responding, it's not even responding at all.  If it did respond, and there was simply a delay to load up the next page, all I'd need is an activity indicator telling me so.  But like I said, the swipe isn't registered at all.

**Comment by guesxy** [comment] 2015-03-29 21:48
I am 2nd gen iPad (which I admin isn't the newest piece of hardware), still running iOS7. And I also dont swipe like crazy, just there is literally a performance lag, which I will try to pin down in one way or another - by paying around with archives and image sizes. I dont think comic sizes did go up, i think most cbr/cbz files are still arodun 30-40 megabytes in size.

**Comment by swisspol** [comment] 2015-03-29 22:48
> What I'm doing is a roughly a 1 second swipe (1 second between touching the iPad before I touch again to swipe again). 

Like I was saying, pages can take more than 1 second to load for comics with high-resolution pages, even on a fancy iPad. What if you do it every 2 seconds or 3 seconds, does it work?

> Comic Zeal page turning is pretty fast, as is Chunky

These might be preprocessing the comics on import or not showing the pages as high-resolutions as ComicFlow.

> When I touchdown again and swipe again, it's not like it's slow responding, it's not even responding at all.

Yes it's always been like that. If you attempt to swipe will the next page is not ready, the app will "hang" while loading it. It should however display it the page once ready.

> I dont think comic sizes did go up, i think most cbr/cbz files are still around 30-40 megabytes in size.

Comic size is irrelevant, what matters is page size. A comic with pages at 1000 pixels resolution will load much faster than one at 3000 pixels.

I would suggest you both try with a comic file using images at around 1500x1000 i.e. close to screen resolution and see if the issue is still here.
